name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.9.0'
        
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install 

    - name: Update the config 
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js

    - name: Start backend
      run:  npm run start:be &
     
    - name: Start frontend
      run:  npm run start:fe &

    - name: Run UI tests
      run: npx playwright test 

  staging_be:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
    - name: Update the config 
      run: echo "export const settings = {host:\"https://ci-cd-librarycatalog.onrender.com"} > src/config.js
    - uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
            service_id: ${{ secrets.RENDER_SERVICE_BE_STAGING_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true

  staging_fe:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
    
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_FE_STAGING_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true
   

  deploy_be:
    needs: staging_be
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_BE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true
  deploy_fe:
    needs: staging_fe
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_FE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true
   
